name: plex
# *****************************************************************************
# Tyzen9 - docker-plex-tautulli
#
# Author: Steve Theisen (https://github.com/tyzen9)
#
# This stack provides a complete self-hosted media solution:
#   - Plex Media Server organizes and streams movies, TV, music, and photos.
#   - Tautulli monitors Plex usage, offering detailed playback and user stats.
#
# Together, they enable both rich media streaming and powerful analytics.
#
# *****************************************************************************

services:
  # *****************************************************************************
  # plex
  #   Plex Media Server organizes and streams personal media collections,
  #   including movies, TV shows, music, and photos, to multiple devices. 
  #   It supports local and remote access, hardware transcoding, and integrates 
  #   with metadata providers to enrich your library. Plex often requires 
  #   `network_mode: host` for proper discovery and DLNA functionality, ensuring 
  #   clients can find the server automatically across the local network.
  #
  # *****************************************************************************
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ_ID}
      - PUID=${PUID:-1000}
      - PGID=${GUID:-1000}
      # - PLEX_CLAIM=claim-xxxxxxxxxxxxxxxxxxxx           # This is needed the first time you run the server to claim it.
      - VERSION=docker
    volumes:
      - plex-config:/config
      - ${BIND_MOUNT_1}
      - ${BIND_MOUNT_2}
      - ${BIND_MOUNT_3}
      - ${BIND_MOUNT_4}
      - ${BIND_MOUNT_5}
      - ${BIND_MOUNT_6}
      - ${BIND_MOUNT_7}
    labels:
      # WUD - What's up docker labels (https://getwud.github.io/wud/#/) -----------
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
      - 'wud.link.template=https://forums.plex.tv/'
      # Offen Backups -------------------------------------------------------------
      - "docker-volume-backup.stop-during-backup=${BACKUP_LABEL}"

  # *****************************************************************************
  # tautulli
  #   Tautulli is a monitoring and analytics tool for Plex Media Server.
  #   It tracks activity such as playback, users, and bandwidth usage,
  #   and provides detailed reports and notifications. Tautulli runs
  #   separately from Plex but connects to it via the API. Typically,
  #   it uses a published port (e.g., 8181) instead of host networking,
  #   since it doesn’t require direct network discovery.
  #
  # *****************************************************************************
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    ports:
      - 8181:8181
    environment:
      - TZ=${TZ_ID}
      - PUID=${PUID:-1000}
      - PGID=${GUID:-1000}
    volumes:
      - tautulli-config:/config
    labels:
      # WUD - What's up docker labels (https://getwud.github.io/wud/#/) -----------
      # Match a single digit first
      - 'wud.tag.include=^[0-9]\.\d+\.\d+$$'
      - 'wud.link.template=https://github.com/Tautulli/Tautulli/releases'
      # Offen Backups -------------------------------------------------------------
      - "docker-volume-backup.stop-during-backup=${BACKUP_LABEL}"

  # *********************************************************************************
  # volume-backup
  #   Automated daily backup of Docker named volumes using offen/docker-volume-backup.
  #   This lightweight service runs in the background, creates a single compressed 
  #   archive containing all specified volumes, and automatically prunes old backups 
  #   based on the configured retention period. It ensures data consistency by 
  #   temporarily stopping labeled containers during the backup process. Backups 
  #   are stored locally on the host; a separate secure process (e.g., rsync/cron) 
  #   can be used for off-site transfer.
  #
  # *********************************************************************************
  volume-backup:
    image: offen/docker-volume-backup:${TAG_OFFEN:-latest}
    container_name: ${BACKUP_LABEL}-backup
    restart: unless-stopped
    depends_on:
      - plex
      - tautulli
    environment:
      - TZ=${TZ_ID:-America/New_York}
      - BACKUP_CRON_EXPRESSION=${BACKUP_CRON_EXPRESSION:-0 2 * * *}
      - BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS:-14}
      - BACKUP_FILENAME=${BACKUP_LABEL}-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_STOP_DURING_BACKUP_LABEL=${BACKUP_LABEL}
      - NOTIFICATION_LEVEL=${BACKUP_NOTIFICATION_LEVEL:-error}
      - NOTIFICATION_URLS=${BACKUP_NOTIFICATION_URLS}          # Comma-separated list of URLs      volumes:
      # Volumes to backup
      - tautulli-config:/backup/tautulli-config:ro                     
      - plex-config:/backup/plex-config:ro                   
      # Local backup location - use a separate secure transfer process to move backups to another host
      - ${BACKUP_LOCAL_TMP_PATH}:/tmp  # Assign a specific tmp dir on the host.  Comment this out to use /tmp
      - ${BACKUP_LOCAL_PATH}:/archive                     
      # Time synch with host to ensure accurate CRON scheduling
      - /etc/localtime:/etc/localtime:ro               
      - /etc/timezone:/etc/timezone:ro                 
      # Allows backup container to control other containers
      - /var/run/docker.sock:/var/run/docker.sock:ro   

    labels:
      # WUD (What's Up Docker) Labels -----------------------------------------------
      # Support leading 'V'
      - 'wud.tag.include=^v\d+\.\d+\.\d+$$'
      - 'wud.link.template=https://github.com/offen/docker-volume-backup/releases'  

# Backup Volumes: tautulli-config, plex-config
# Note: The plex-config-media volume contains “Optimized for Mobile” and “Intro Detection”
#       This volume is optional to backup, Plex can rebuild this for you. 
volumes:
  tautulli-config:
  plex-config:
  plex-config-media:
